### ISSUE TITLE
Socket.io update changes behavior

### ISSUE THREAD

**Issue by wagnerec** [leftyfl1p/homebridge-poolcontroller#2]
Did a fresh install and the socket.io behavior changes a bit. Fix was:
Line 41, reconnect had to be changed to reconnection
Line 59, change from 
    for (var i = 0; i < circuitData.length; i++)
to
    for( i in circuitData)
same for line 106

**Comment by leftyfl1p** [comment]
Take a look at the refactor branch, the entire thing has been rewritten to be updated with the new pool-controller API. The current branch is pretty outdated and we should probably merge the two anyways.

**Comment by leftyfl1p** [comment]
Closing as inactive.
