### ISSUE TITLE
Request: Hayward OmniHub compatibility?

### ISSUE THREAD

**Issue by mikesalz** [leftyfl1p/homebridge-poolcontroller#8]
Is there any chance that this is - or can be - compatible with the Hayward OmniHub system?
https://www.hayward-pool.com/shop/en/pools/omnihub

They claim it works with Amazon, Nest, Control4, and Crestron.  They should definitely list Homebridge too! :)

**Comment by leftyfl1p** [comment]
This plugin is for poolcontroller. If it works with poolcontroller it should work with this otherwise this is not a pool specific plugin.
